# kubectl create secret tls FIRST_SECRET_NAME --cert FIRST_CERT_FILE --key FIRST_KEY_FILE

apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: default
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls